# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Arvind testing

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'app_version for the build'
        required: true
        default: 'latest'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Build & Test
      run: ./gradlew clean build
      
    - name: Backup Builds
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Jar File
        path: |
          build/libs/demo-0.0.1-SNAPSHOT.jar
